easy_admin:
    site_name: 'TutoMarks'
    user:
        name_property_path: 'username'
    entities:
        User:
            class: App\Entity\User
            list:
                fields: ['username', 'email', 'roles', 'is_actif', 'tutos', 'created_at', 'last_connection']
            form:
                fields:
                    - username
                    - email
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                    - is_actif
        Tags:
            class: App\Entity\Tags
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'image', type: 'image', base_path: '%uploads_path%/tags/' }
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'imageFile', type: 'vich_image' }
        Categories:
            class: App\Entity\Categories
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'title'}
                    - { property: 'logo'}
                    - { property: 'tutos'}
                    - { property: 'homekey'}
                    - { property: 'withVideos'}
                    - { property: 'image', type: 'image', base_path: '%uploads_path%/categories/' }
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'logo' }
                    - { property: 'tutos' }
                    - { property: 'homekey' }
                    - { property: 'withVideos' }
                    - { property: 'imageFile', type: 'vich_image' }
        Prices:
            class: App\Entity\Prices
            list:
                fields: ['id', 'name']
            form:
                fields: ['name']
        Levels:
            class: App\Entity\Levels
            list:
                fields: ['id', 'name', 'rank']
            form:
                fields: ['name', 'rank']
        Comments:
            class: App\Entity\Comments
            list:
                fields: ['id', 'user', 'tutos', 'commented_at', 'is_validate']
            form:
                fields: ['user', 'tutos', 'commented_at', 'comment', 'is_validate']
        Langues:
            class: App\Entity\Langues
            list:
                fields: ['id', 'name', 'shortname', 'logo']
            form:
                fields: ['name', 'shortname', 'logo']
        Channels:
            class: App\Entity\Channels
            list:
                fields: ['id', 'title', 'site_url', 'youtube_id', 'youtube_custom_url', 'thumbnails_url', 'twitter', 'github']
            form:
                fields: ['title', 'site_url', 'youtube_id', 'youtube_custom_url', 'thumbnails_url', 'twitter', 'github']
        Tutos:
            class: App\Entity\Tutos
            list:
                fields: ['id', 'title', 'published_by', 'published_at', 'creator', 'channel', 'url', 'category', 'langue', 'youtube_id']
            form:
                fields: ['title', 'published_by', 'published_at', 'creator', 'channel', 'url', 'category', 'tags', 'description', 'langue', 'youtube_id']
        Badges:
            class: App\Entity\Badges
            list:
                fields: ['id', 'name', 'action_name', 'action_count', 'image']
            form:
                fields: ['name', 'action_name', 'action_count', 'image']
        UserTutosInformations:
            class: App\Entity\UserTutosInformations
            list:
                fields: ['id', 'user', 'tutos', 'shown', 'pined']
            form:
                fields: ['user', 'tutos', 'shown', 'pined']
