easy_admin:
    site_name: 'TutoMarks'
    user:
        name_property_path: 'username'
    entities:
        User:
            class: App\Entity\User
            list:
                fields: ['username', 'email', 'roles', 'is_actif', 'tutos', 'created_at', 'last_connection']
            form:
                fields:
                    - username
                    - email
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                    - is_actif
        Tags:
            class: App\Entity\Tags
            list:
                fields: ['id', 'title', 'logo']
            form:
                fields: ['title', 'logo']
        Categories:
            class: App\Entity\Categories
            list:
                fields: ['id', 'title', 'logo', 'tutos']
            form:
                fields: ['title', 'logo']
        Prices:
            class: App\Entity\Prices
            list:
                fields: ['id', 'name']
            form:
                fields: ['name']
        Levels:
            class: App\Entity\Levels
            list:
                fields: ['id', 'name', 'rank']
            form:
                fields: ['name', 'rank']
        Comments:
            class: App\Entity\Comments
            list:
                fields: ['id', 'user', 'tutos', 'commented_at', 'is_validate']
            form:
                fields: ['user', 'tutos', 'commented_at', 'comment', 'is_validate']
        Langues:
            class: App\Entity\Langues
            list:
                fields: ['id', 'name', 'shortname', 'logo']
            form:
                fields: ['name', 'shortname', 'logo']
        Tutos:
            class: App\Entity\Tutos
            list:
                fields: ['id', 'title', 'published_by', 'published_at', 'creator', 'url', 'category', 'langue']
            form:
                fields: ['title', 'published_by', 'published_at', 'creator', 'url', 'category', 'tags', 'description', 'langue']
        Badges:
            class: App\Entity\Badges
            list:
                fields: ['id', 'name', 'action_name', 'action_count', 'image']
            form:
                fields: ['name', 'action_name', 'action_count', 'image']
        UserTutosInformations:
            class: App\Entity\UserTutosInformations
            list:
                fields: ['id', 'user', 'tutos', 'shown', 'pined']
            form:
                fields: ['user', 'tutos', 'shown', 'pined']