vich_uploader:
    db_driver: orm

    mappings:
        tags_images:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public%uploads_path%'
            namer: vich_uploader.namer_origname
            inject_on_load: false
        authors_images:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public%uploads_path%'
            namer: vich_uploader.namer_origname
            inject_on_load: false
        categories_images:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public%uploads_path%'
            namer: vich_uploader.namer_origname
            inject_on_load: false
        languages_images:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public%uploads_path%'
            namer: vich_uploader.namer_origname
            inject_on_load: false
        simple_links_images:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public%uploads_path%'
            namer: vich_uploader.namer_origname
            inject_on_load: false