version: '3.3'

services:
    mysqldb:
        image: mysql/mysql-server:5.7
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            #            - "./data/db/mysql:/var/lib/mysql"
            - mysqlsb_data:/var/lib/mysql
            - ./services/mysql/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf:ro
        ports:
            - "3306:3306"

volumes:
    mysqlsb_data:
        driver: local